services:
  app:
    build: .
    env_file: .env
    environment:
      HOST: 0.0.0.0
    expose:
      - "8000"
    networks:
      proxy:
        aliases:
          - utc-app
    restart: unless-stopped

networks:
  proxy:
    external: true
